build:
  image: gwq-vpgitlab01.gwq-serviceplus.de:5005/base/sync/docker:cli
  stage: build
  services:
    - name: gwq-vpgitlab01.gwq-serviceplus.de:5005/base/sync/docker:dind
      alias: docker
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  tags:
    - online
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t "$DOCKER_IMAGE_NAME" .
    - docker push "$DOCKER_IMAGE_NAME" 