version: '3.8'

services:
  theme-builder:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - theme-output:/build-output
    command: >
      sh -c "cp dist_keycloak/*.jar /build-output/"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "${KC_PORT:-8087}:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KC_BOOTSTRAP_ADMIN_USERNAME:-admin}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KC_BOOTSTRAP_ADMIN_PASSWORD:-admin}
    volumes:
      - theme-output:/opt/keycloak/providers/
    command: start-dev
    depends_on:
      - theme-builder

volumes:
  theme-output:
