name: Code Quality

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.0

      - name: Install dependencies
        run: pnpm install

      - name: Run unit tests
        run: pnpm run test --if-present

      - name: Check code formatting
        run: npx prettier --check .

      - name: Check code linting
        run: npx eslint . --max-warnings 0

      - name: Check build
        run: pnpm run build

      - name: Run Security Audit
        run: pnpm audit

      - name: Build Project
        run: pnpm run build
